[project]
name = "adventofcode"
version = "0.1.0"
description = "virtual env for advent of code"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "pyperclip>=1.11.0",
    "requests>=2.32.5",
    "rich>=14.2.0",
]
